### ISSUE TITLE
Anam not loading non-standard height values correctly

### ISSUE THREAD

**Issue by Raziek** [imchillin/Anamnesis#1211]
Possibly related to https://github.com/imchillin/Anamnesis/pull/1204

Currently the height field appears to be functioning as a multiplier to the character's height, which is producing incorrect sizes for anyone who plays with heights outside the default sliders. As it stands, this value always defaults to 1 for an unmodified character.
![image](https://user-images.githubusercontent.com/112226566/187011476-5ca591b2-2e1e-4388-8ec8-262e38415079.png)

**Steps to Reproduce:**

A max height Rava has a height value of **191cm or 75 inches**

If one were to (using Textools) modify the racial scale of said Rava to **1.85**, it produces a height of **117.3** inches in the character creation menu.

If 1.85 is instead input in the **height** field, the result is Anam multiplies 75 inches by 1.85, producing a total height of **138.75** inches, which substantially overshoots the correct value.

**Expected behaviour**
Previous builds of Anamnesis tied the height value to the racial scaling parameters, so a max height Rava would load with a height value of 1.189 instead of a value of 1. Adjusting the "Height' Field to 1.85 should result in the same result as editing the racial scaling, of 117.3 inches.

**Comment by AsgardXIV** [comment]
Yes, this is the same issue as #1204 and is fixed in the next release.

**Comment by Raziek** [comment]
Wonderful, apologies for my misunderstanding! Thought 1204 was in the current release and thus it was still an issue.
