### ISSUE TITLE
Failed to initialize service: LocalizationService

### ISSUE THREAD

**Issue by jonorama** [imchillin/Anamnesis#335]
[2021-04-30-16-23-42.txt](https://github.com/imchillin/Anamnesis/files/6407889/2021-04-30-16-23-42.txt)

**Comment by jonorama** [comment]
[2021-04-30-16-28-09.txt](https://github.com/imchillin/Anamnesis/files/6407895/2021-04-30-16-28-09.txt)
[2021-04-30-16-28-09.txt](https://github.com/imchillin/Anamnesis/files/6407896/2021-04-30-16-28-09.txt)
[2021-04-30-16-28-09.txt](https://github.com/imchillin/Anamnesis/files/6407899/2021-04-30-16-28-09.txt)

**Comment by Yuuki-Walsh** [comment]
hmm. Are you on the latest version? This appears to be #296 which was fixed with the 2021-04-24 release.
If anamnesis isn't launching it also wont update itself, so you may need to download the <a href="https://github.com/imchillin/Anamnesis/releases"> latest release</a> manually.

**Comment by XilloTV** [comment]
@Yuuki-Walsh This is the updated version. It has crashed numerously after updating as well. I was originally using the 2021-04-24 release and updated to the 5.5 hotfix when it prompted me to. The program works fine for a while but after the first crash I can't click anything on the window. I force close the window and then I get memory errors upon trying to boot it back up. It still opens the window after giving me errors, but I cannot use any of the features. The only fix is to completely delete the folder and restart the game and extract the file again.

**Comment by jonorama** [comment]
I got the new one that you linked and it still wont open. same issue
[2021-05-02-16-08-45.txt](https://github.com/imchillin/Anamnesis/files/6412156/2021-05-02-16-08-45.txt)

**Comment by jonorama** [comment]
[2021-05-02-16-08-45.txt](https://github.com/imchillin/Anamnesis/files/6412158/2021-05-02-16-08-45.txt)

**Comment by Yuuki-Walsh** [comment]
Do the "Languages" and "Data" folders exist next to your Anamnesis.exe file?

**Comment by jonorama** [comment]
![Screenshot (3)](https://user-images.githubusercontent.com/83475636/117489031-18446980-af3b-11eb-984d-e3b227bc5678.png)

**Comment by jonorama** [comment]
that's everything in the folder

**Comment by Yuuki-Walsh** [comment]
is this still happening with the most recent builds?

**Comment by Ani-ki** [comment]
@jonorama are you still having this issue?

**Comment by jonorama** [comment]
Im going to test it out today!

**Comment by jonorama** [comment]
I've finally been able to bring it up! Ill now tinker with it. The only issue I see now is I can't have the program on my desktop . I have to keep it in the folder after I extract it.
