### ISSUE TITLE
Actor Motion Disabled not registering

### ISSUE THREAD

**Issue by meajora** [imchillin/Anamnesis#351]
![image](https://user-images.githubusercontent.com/83964412/117669823-5036f100-b175-11eb-8061-3547c4b981c1.png)
Shows that Actor motion must be disabled in the group pose settings, even though actor motion is already disabled. Have restarted anamnesis, restarted gpose, and the error message does not leave.

**Comment by Ani-ki** [comment]
Can confirm I was able to get the issue myself earlier today, so we now have a reference point for research into why this is occurring.

**Comment by Yuuki-Walsh** [comment]
> What I'm finding is that, if there are things that are in the vicinity that can't be paused such as other PCs or bestiary for x,y reason, it's still counting them toward the 'things not being paused' check.

Seems like it may be related to non frozen actors nearby.

**Comment by icy-** [comment]
Had this issue.  Found workaround -- I ported to secluded area with my buddy, e.g. to Central Thanalan.   Checked the actors noted by Anamnesis.  It only had our two minions and us (I only added the two of us).  Issue persisted.
After we both dismissed minions, the issue went away.   I was able to successfully do Think! emote from Cap'n =)

**Comment by icy-** [comment]
btw the issue could be reproduced like so (based on my discord comments)
0) add another person to party and with Anamnesis "+" 
1) enter gpose
2) disable motion or each target one by one, doesnt matter
3) Anamnesis popup goes away (good)
4) change to another "+"'d targets on the left inside Anamnesis
5) popup comes back :frowning:

I had been in Lavender Beds just outside, with loads of actors in the vicinity previously (striking dummies etc), so not sure if when we both dismissed minions that is enough to work around, or if the dismissing AND secluded area is needed

**Comment by Yuuki-Walsh** [comment]
Possibly fixed with 0f638790deb383282f578bd463fcd046678c740f

**Comment by meajora** [comment]
I'm still having this issue. I even tried inside an apartment with no NPCs, just my character and a carbuncle, both frozen, and the pop-up occurred for both actors. Confirmed with Anamnesis only the two actors existed. No minions.

**Comment by Ani-ki** [comment]
Per Yuuki's comment before yours, this has been fixed in the next build, due shortly.
