### ISSUE TITLE
Error: Failed to filter selection item

### ISSUE THREAD

**Issue by unknownuserxv** [imchillin/Anamnesis#468]
Failed to filter selection item: Anamnesis.GameData.ViewModels.ItemViewModel
Rest is long so on image. The program opens endless windows with this error and has to be forced to close with task manager, I found that just opening the program or trying to use it is enough to cause the issue.

Sadly can't put the error screenshot here so https://imgur.com/a/GbB2nAa.

Also at the same time this error happened if I change my actor from male to female no clothes but the racial and npc, invisible options exist.

**Comment by ajiiisai** [comment]
Fixed on b8a1319

**Comment by Ani-ki** [comment]
This is being covered in #467. Closed due to duplicate issue.

**Comment by NevaehRose** [comment]
> Fixed on [b8a1319](https://github.com/imchillin/Anamnesis/commit/b8a1319a58a15ab2cb906a75ca3fc849c36b738e)

Hi i see that its been fixed but im still having this issue. I even removed anamnesis completely and downloaded the new release and im still having this issue

**Comment by ajiiisai** [comment]
Could you provide some logs please?
