### ISSUE TITLE
anamnesis not registering npcs

### ISSUE THREAD

**Issue by faeneptune** [imchillin/Anamnesis#521]
Spoke with a moderator in the discord about this, they told me to submit an issue here, but i cant seem to get anamnesis to register npcs, literally any of them. Whenever i go into gpose the add character list does not show NPCs even with the option selected, i can select them outside of gpose, but the minute i do /gpose the npc list disappears and even when i have already added them to the pose list, it removes them and says "this actor has no model" attached files will show, as well as my most recently generated log and i am also fully updated 
![3b100d7a8ed8c1b96b264f512206180d](https://user-images.githubusercontent.com/91155241/134232331-1de21b57-9bbe-4472-900b-06420bf3a251.png)
![Untitled](https://user-images.githubusercontent.com/91155241/134232339-a4704204-89a2-454b-8d4b-128b1beb1339.png)
[2021-09-21-14-45-17.txt](https://github.com/imchillin/Anamnesis/files/7205597/2021-09-21-14-45-17.txt)

**Comment by Ani-ki** [comment]
Many thanks for the detailed report. We will be able to investigate this further later today, and may need to ask a few additional questions.

**Comment by faeneptune** [comment]
Of course! Lemme know if you want my discord information, or let me know if you want me to shoot you a message so you have it, i just joined the server today

**Comment by Yuuki-Walsh** [comment]
can you target them in-game while in gpose?
If you cannot target them in-game while in gpose, then they did not enter gpose with you, so you cant select them.

Changing them to a "battle npc" or "player" outside of gpose first might help, but how the game chooses who to bring into gpose with you can be a bit wonky.

**Comment by Yuuki-Walsh** [comment]
should be fixed along with #525 by teh same change

**Comment by faeneptune** [comment]
I dont know if replying from the email link works to get to you, but
updated, still didnt change, and so i completely removed all files from my
computer and reinstalled and i am still not able to target npc's in /gpose.
Its not like, the biggest issue but like i know i should be able to i just
have no idea if im missing something or if something is wrong or what but i
am getting all the same errors as i was when i first submitted a ticket

**Comment by faeneptune** [comment]
For context, again, all im doing is standing in the Rising Stones, near the
end of 5.5 msq, with all the scions and i just wanted to take a "scion
family" picture, i have seen multiple other people who have all said they
used anamnesis to pose them pose them literally EXACTLY where i am and with
what im doing

**Comment by Ani-ki** [comment]
> still not able to target npc's in /gpose.
You cannot target actors while in GPose. You must add them outside of GPose.

**Comment by faeneptune** [comment]
Oh i see what you mean, and now the issue of moving them once ive already
added them prior to /gpose is actually fixed, i dont know if this is just
the limitations so one final question is, i cant disable their movement to
move them as a whole im assuming that is also normal?

**Comment by faeneptune** [comment]
So, Tried something with my boyfriend, i am apparently not able to select
npcs at all, in the base game in gpose, he went into the inn in foundation
and showed me he can just go into gpose and then select an npc to focus on,
my game WILL not do this, we tried a lot of different things, so HONESTLY
the issue might not even be with Anamnesis at this point, i might just have
to reinstall 14 on my end all together, either way you all have been
patient and helpful, if i ever figure it out ill will update this thread.
