### ISSUE TITLE
Tool sometimes doesn't refresh actor

### ISSUE THREAD

**Issue by damphands** [imchillin/Anamnesis#614]
**Describe the bug**
Occasionally the tool will fail to refresh the actor, especially when moving through options quickly.

**To Reproduce**
Steps to reproduce the behaviour:
Move through options quickly while changing characters appearances or models.

**Expected behaviour**
The tool refreshes the actor every time a change is selected/made. 

**Log file**
Will provide log files from users reporting the issue in comments.

**Comment by damphands** [comment]
[2021-11-08-13-34-36.txt](https://github.com/imchillin/Anamnesis/files/7497088/2021-11-08-13-34-36.txt)

**Comment by b2aspirit** [comment]
[2021-11-08-13-04-27.txt](https://github.com/imchillin/Anamnesis/files/7500161/2021-11-08-13-04-27.txt)
for that run though on self , it didn't fail to refresh , but the other actor had a few non refreshes before it forced refresh by something else 
21417075733282141707573328 <--- it was this character that actor refresh wasn't going

**Comment by Yuuki-Walsh** [comment]
This is fixed for the next release.

**Comment by damphands** [comment]
Can confirm this issue persists in latest release. Will provide video evidence. May be hardware related, since Aniki and yuuki cannot replicate.

**Comment by damphands** [comment]
[2021-11-14-20-53-33.txt](https://github.com/imchillin/Anamnesis/files/7533554/2021-11-14-20-53-33.txt)

https://www.youtube.com/watch?v=Aep4btVG7qc

**Comment by damphands** [comment]
Fixed in latest release
